apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: cloud-native-weather-vue
    newName: ghcr.io/qaware/cloud-native-weather-vue3
    newTag: 1.0.0

resources:
  - ../../base/