apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cloud-native-weather-vue3
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloud-native-weather-vue3
  validation: client
  targetNamespace: default
  images:
    - name: cloud-native-weather-vue3
      newName: ghcr.io/qaware/cloud-native-weather-vue3 # {"$imagepolicy": "flux-system:cloud-native-weather-vue3:name"}
      newTag: 1.0.0 # {"$imagepolicy": "flux-system:cloud-native-weather-vue3:tag"}