apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: weather-frontend
  framework: vue3

buildMetadata: [managedByLabel]

resources:
  - vue-deployment.yaml
  - vue-service.yaml