apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  selector:
    matchLabels:
      app: vue-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: vue-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: cloud-native-weather-vue
          image: cloud-native-weather-vue
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000

          #lifecycle:
            #preStop:
              #exec:
                #command: ["/usr/sbin/nginx","-s","quit"]