apiVersion: v1
kind: Service
metadata:
  name: vue-frontend
spec:
  type: ClusterIP
  selector:
    app: vue-frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
