apiVersion: v1
kind: Service
metadata:
  name: vue-frontend
spec:
  selector:
    app: weather-service
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer